### ISSUE TITLE
Lack of User-Defined Initial State

### ISSUE THREAD

**Issue by Lilyy200** [gasp002/Gameoflife-Gaspard-DIA5#4]
Hey !
The current implementation of the Conway's Game of Life simulation has a hardcoded initial state in the main function. To make the project more flexible and user-friendly, an improvement can be made to allow users to define their initial state by providing custom patterns or loading preset configurations.

**Comment by gasp002** [comment]
okay that could be a good idea !

**Comment by gasp002** [comment]
Maybe create a function to show the user initial state
